"""Add specialties column

Revision ID: 786a83165b7c
Revises: 003_add_ratings
Create Date: 2026-02-07 13:27:31.354348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786a83165b7c'
down_revision = '003_add_ratings'
branch_labels = None
depends_on = None


def upgrade():
    # Check existing schema
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Handle comments table
    comments_indexes = [idx['name'] for idx in inspector.get_indexes('comments')]
    if 'idx_comment_post_author' in comments_indexes:
        with op.batch_alter_table('comments', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('idx_comment_post_author'))

    # Handle communities table
    communities_columns = [col['name'] for col in inspector.get_columns('communities')]
    with op.batch_alter_table('communities', schema=None) as batch_op:
        if 'category' not in communities_columns:
            batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        if 'creator_id' not in communities_columns:
            batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    # Handle posts table
    posts_indexes = [idx['name'] for idx in inspector.get_indexes('posts')]
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        if 'ix_posts_title' in posts_indexes:
            batch_op.drop_index(batch_op.f('ix_posts_title'))

    # Handle users table
    users_columns = [col['name'] for col in inspector.get_columns('users')]
    if 'specialties' not in users_columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('specialties', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('specialties')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_title'), ['title'], unique=False)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('category')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_comment_post_author'), ['post_id', 'author_id'], unique=False)

    # ### end Alembic commands ###
