"""Add community_id to comments

Revision ID: a5ff909971d3
Revises: 
Create Date: 2026-02-12 00:20:50.567916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ff909971d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_comments_community_id'), ['community_id'], unique=False)
        batch_op.create_foreign_key('fk_comments_community_id', 'communities', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_community_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comments_community_id'))
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###
